
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [pre-commit]
        language: system
        entry: isort
        types: [python]

      - id: black
        name: black
        stages: [pre-commit]
        language: system
        entry: black
        types: [python]

      - id: autoflake
        name: autoflake
        stages: [pre-commit]
        language: system
        entry: autoflake
        types: [python]

      - id: flake8
        name: flake8
        stages: [pre-commit]
        language: system
        entry: flake8
        types: [python]